repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=50000']

-   repo: https://github.com/aio-libs/sort-all
    rev: v1.3.0
    hooks:
    -   id: sort-all

-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        additional_dependencies:
        - Flake8-pyproject==1.2.4
        - flake8-bugbear==25.11.29
        - pep8-naming==0.14.1

-   repo: https://github.com/python-poetry/poetry
    rev: 2.4.1
    hooks:
    -   id: poetry-check
        args: ['--lock', '--no-cache']
        stages: [pre-push]
    -   id: poetry-lock
        args: ['--no-cache']
        stages: [pre-push]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
    -   id: commitizen
    -   id: commitizen-branch
        stages: [pre-push]

-   repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
    -   id: nbstripout
        files: \.ipynb$

-   repo: local
    hooks:
    -   id: cruft-check
        name: cruft-check
        entry: bash -c 'cruft check'
        language: python
        pass_filenames: false
        stages: [pre-push]
