repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=50000']

-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort

-   repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
    -   id: black
        language_version: python3.14

-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        additional_dependencies: [Flake8-pyproject]

-   repo: https://github.com/python-poetry/poetry
    rev: 2.4.0
    hooks:
    -   id: poetry-check
        args: ['--lock', '--no-cache']
        stages: [pre-push]
    -   id: poetry-lock
        args: ['--no-cache']
        stages: [pre-push]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.10
    hooks:
    -   id: commitizen
    -   id: commitizen-branch
        stages: [pre-push]

-   repo: local
    hooks:
    -   id: cruft-check
        name: cruft-check
        entry: bash -c 'cruft check'
        language: python
        pass_filenames: false
        stages: [pre-push]
