from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from math import isqrt
from typing import Literal

import numpy as np
import numpy.typing as npt

from qlinks.qec.code_space import CodeSpace
from qlinks.qec.error_sets import ErrorOperator, LocalErrorSet
from qlinks.qec.knill_laflamme import apply_error_to_code

ErrorAlgebraClassification = Literal[
    "scalar_algebra_subspace_code",
    "full_matrix_algebra_no_protected_subsystem",
    "subsystem_code_candidate",
    "hybrid_block_or_subsystem_candidate",
    "classical_block_structure",
    "irreducible_nonfull_inconclusive",
]


@dataclass(frozen=True, slots=True)
class ProjectedErrorAlgebraReport:
    """Algebra generated by projected QEC error products inside a code manifold.

    The generated algebra is the unital algebra spanned by products of
    ``P E_a^dagger E_b P`` represented in the orthonormal code basis.  Its
    commutant is the algebra of code-space operators that commute with all
    projected error products.  A nontrivial commutant is the first signal that
    the candidate may contain a protected subsystem even when ordinary subspace
    KL conditions fail.
    """

    code_dimension: int
    error_set_name: str
    n_errors: int
    n_projected_error_products: int
    generator_span_dimension: int
    algebra_dimension: int
    commutant_dimension: int
    center_dimension: int
    tolerance: float
    classification: ErrorAlgebraClassification
    algebra_basis: tuple[npt.NDArray[np.complex128], ...] = field(default=(), repr=False)

    @property
    def full_matrix_algebra_dimension(self) -> int:
        return self.code_dimension * self.code_dimension

    @property
    def has_nontrivial_commutant(self) -> bool:
        return self.commutant_dimension > 1

    @property
    def has_nontrivial_center(self) -> bool:
        return self.center_dimension > 1

    @property
    def candidate_subsystem_dimension(self) -> int | None:
        """Return ``sqrt(commutant_dimension)`` when it is a plausible factor size.

        For an ideal factor decomposition ``A_err = M_n ⊗ I_m``, the commutant
        has dimension ``m^2``.  The returned value is therefore only a quick
        screening hint, not a certified tensor-factor decomposition.
        """
        if self.center_dimension != 1 or self.commutant_dimension <= 1:
            return None
        root = isqrt(self.commutant_dimension)
        if root * root != self.commutant_dimension:
            return None
        return root

    @property
    def interpretation(self) -> str:
        if self.classification == "scalar_algebra_subspace_code":
            return "projected errors are scalar on the whole code space"
        if self.classification == "full_matrix_algebra_no_protected_subsystem":
            return "projected errors generate the full logical matrix algebra"
        if self.classification == "subsystem_code_candidate":
            return "projected errors have a nontrivial commutant; inspect subsystem factors"
        if self.classification == "hybrid_block_or_subsystem_candidate":
            return "projected errors show block structure and a nontrivial commutant"
        if self.classification == "classical_block_structure":
            return "projected errors separate classical blocks, with no evident quantum subsystem"
        return "commutant is scalar but the generated algebra is not numerically full"

    def to_summary_dict(self) -> dict[str, object]:
        """Return a compact, serialization-friendly projected-algebra summary."""
        return {
            "code_dimension": self.code_dimension,
            "error_set_name": self.error_set_name,
            "n_errors": self.n_errors,
            "n_projected_error_products": self.n_projected_error_products,
            "generator_span_dimension": self.generator_span_dimension,
            "algebra_dimension": self.algebra_dimension,
            "full_matrix_algebra_dimension": self.full_matrix_algebra_dimension,
            "commutant_dimension": self.commutant_dimension,
            "center_dimension": self.center_dimension,
            "has_nontrivial_commutant": self.has_nontrivial_commutant,
            "has_nontrivial_center": self.has_nontrivial_center,
            "candidate_subsystem_dimension": self.candidate_subsystem_dimension,
            "classification": self.classification,
            "interpretation": self.interpretation,
            "tolerance": self.tolerance,
        }

    def to_text(self) -> str:
        """Return a human-readable projected-error-algebra summary."""
        from qlinks.qec.reporting import format_bool, format_key_value_lines

        return format_key_value_lines(
            f"Projected error algebra: {self.error_set_name}",
            (
                ("code dimension", self.code_dimension),
                ("errors", self.n_errors),
                ("projected E†E products", self.n_projected_error_products),
                ("generator span dimension", self.generator_span_dimension),
                ("algebra dimension", self.algebra_dimension),
                ("full matrix dimension", self.full_matrix_algebra_dimension),
                ("commutant dimension", self.commutant_dimension),
                ("center dimension", self.center_dimension),
                ("nontrivial commutant", format_bool(self.has_nontrivial_commutant)),
                ("nontrivial center", format_bool(self.has_nontrivial_center)),
                ("candidate subsystem dimension", self.candidate_subsystem_dimension),
                ("classification", self.classification),
                ("interpretation", self.interpretation),
            ),
        )

    def format_summary(self) -> str:
        return self.to_text()

    def __str__(self) -> str:
        return self.to_text()

    def __rich__(self):
        return self.to_rich()

    def to_rich(self):
        """Return a rich renderable projected-error-algebra summary."""
        from qlinks.qec.reporting import add_summary_rows, format_bool, require_rich

        _group, Panel, Table, _text = require_rich("ProjectedErrorAlgebraReport")
        table = Table.grid(padding=(0, 2))
        table.add_column(style="bold")
        table.add_column()
        add_summary_rows(
            table,
            (
                ("code dimension", self.code_dimension),
                ("errors", self.n_errors),
                ("projected E†E products", self.n_projected_error_products),
                ("generator span dimension", self.generator_span_dimension),
                ("algebra dimension", self.algebra_dimension),
                ("full matrix dimension", self.full_matrix_algebra_dimension),
                ("commutant dimension", self.commutant_dimension),
                ("center dimension", self.center_dimension),
                ("nontrivial commutant", format_bool(self.has_nontrivial_commutant)),
                ("nontrivial center", format_bool(self.has_nontrivial_center)),
                ("candidate subsystem dimension", self.candidate_subsystem_dimension),
                ("classification", self.classification),
                ("interpretation", self.interpretation),
            ),
        )
        return Panel(table, title=f"Projected error algebra: {self.error_set_name}")


def diagnose_projected_error_algebra(
    code_space: CodeSpace,
    errors: LocalErrorSet | Sequence[ErrorOperator],
    *,
    max_weight: int | None = None,
    tolerance: float = 1e-10,
    max_iterations: int = 100,
) -> ProjectedErrorAlgebraReport:
    """Diagnose the algebra generated by ``P E_a^dagger E_b P``.

    This is the natural follow-up when ordinary subspace KL fails.  If the
    projected error algebra is not scalar but has a nontrivial commutant, the
    cage manifold may still contain a protected subsystem/logical algebra.  If
    the algebra is the full ``K × K`` matrix algebra, local errors can resolve
    the whole candidate manifold.
    """
    error_set_name, error_list = _normalize_errors(errors)
    if max_weight is not None:
        max_weight = int(max_weight)
        error_list = tuple(error for error in error_list if error.weight <= max_weight)
        error_set_name = f"{error_set_name}_w{max_weight}"

    dimension = code_space.dimension
    full_dimension = dimension * dimension
    identity = np.eye(dimension, dtype=np.complex128)

    generator_builder = _MatrixSpanBuilder(
        dimension=dimension,
        tolerance=tolerance,
        max_dimension=full_dimension,
    )
    generator_builder.try_add(identity)

    error_images = tuple(apply_error_to_code(code_space, error.operator) for error in error_list)
    for left_image in error_images:
        for right_image in error_images:
            generator_builder.try_add(left_image.conj().T @ right_image)
            if generator_builder.dimension == full_dimension:
                break
        if generator_builder.dimension == full_dimension:
            break

    generators = generator_builder.basis_matrices
    algebra_basis = _generate_unital_algebra_basis(
        generators,
        tolerance=tolerance,
        max_iterations=max_iterations,
    )
    commutant_dimension = _commutant_dimension(generators, tolerance=tolerance)
    center_dimension = _center_dimension(
        algebra_basis,
        generators,
        tolerance=tolerance,
    )
    classification = _classify_error_algebra(
        code_dimension=dimension,
        algebra_dimension=len(algebra_basis),
        commutant_dimension=commutant_dimension,
        center_dimension=center_dimension,
    )

    return ProjectedErrorAlgebraReport(
        code_dimension=dimension,
        error_set_name=error_set_name,
        n_errors=len(error_list),
        n_projected_error_products=len(error_list) * len(error_list),
        generator_span_dimension=len(generators),
        algebra_dimension=len(algebra_basis),
        commutant_dimension=commutant_dimension,
        center_dimension=center_dimension,
        tolerance=tolerance,
        classification=classification,
        algebra_basis=algebra_basis,
    )


class _MatrixSpanBuilder:
    def __init__(self, *, dimension: int, tolerance: float, max_dimension: int) -> None:
        self._dimension = int(dimension)
        self._tolerance = float(tolerance)
        self._max_dimension = int(max_dimension)
        self._basis_vectors: list[npt.NDArray[np.complex128]] = []
        self._basis_matrices: list[npt.NDArray[np.complex128]] = []

    @property
    def dimension(self) -> int:
        return len(self._basis_matrices)

    @property
    def basis_matrices(self) -> tuple[npt.NDArray[np.complex128], ...]:
        return tuple(self._basis_matrices)

    def try_add(self, matrix: npt.ArrayLike) -> bool:
        if self.dimension >= self._max_dimension:
            return False

        arr = np.asarray(matrix, dtype=np.complex128)
        if arr.shape != (self._dimension, self._dimension):
            raise ValueError(
                f"Expected matrix shape ({self._dimension}, {self._dimension}), got {arr.shape}."
            )

        vector = arr.reshape(-1).astype(np.complex128, copy=True)
        original_norm = float(np.linalg.norm(vector))
        if original_norm <= self._tolerance:
            return False

        residual = vector.copy()
        for basis_vector in self._basis_vectors:
            residual -= np.vdot(basis_vector, residual) * basis_vector

        residual_norm = float(np.linalg.norm(residual))
        threshold = self._tolerance * max(1.0, original_norm)
        if residual_norm <= threshold:
            return False

        normalized = residual / residual_norm
        self._basis_vectors.append(normalized)
        self._basis_matrices.append(normalized.reshape(self._dimension, self._dimension))
        return True


def _generate_unital_algebra_basis(
    generators: Sequence[npt.NDArray[np.complex128]],
    *,
    tolerance: float,
    max_iterations: int,
) -> tuple[npt.NDArray[np.complex128], ...]:
    if len(generators) == 0:
        raise ValueError("At least one generator is required.")

    dimension = int(generators[0].shape[0])
    full_dimension = dimension * dimension
    builder = _MatrixSpanBuilder(
        dimension=dimension,
        tolerance=tolerance,
        max_dimension=full_dimension,
    )
    for generator in generators:
        builder.try_add(generator)

    generator_tuple = builder.basis_matrices
    iteration = 0
    changed = True
    while changed and builder.dimension < full_dimension:
        iteration += 1
        if iteration > max_iterations:
            raise RuntimeError(
                "Projected error algebra closure did not converge within "
                f"max_iterations={max_iterations}."
            )
        changed = False
        current_basis = builder.basis_matrices
        for basis_matrix in current_basis:
            for generator in generator_tuple:
                changed = builder.try_add(basis_matrix @ generator) or changed
                if builder.dimension >= full_dimension:
                    break
                changed = builder.try_add(generator @ basis_matrix) or changed
                if builder.dimension >= full_dimension:
                    break
            if builder.dimension >= full_dimension:
                break

    return builder.basis_matrices


def _commutant_dimension(
    generators: Sequence[npt.NDArray[np.complex128]],
    *,
    tolerance: float,
) -> int:
    if len(generators) == 0:
        return 0
    dimension = int(generators[0].shape[0])
    identity = np.eye(dimension, dtype=np.complex128)
    constraints = [
        np.kron(generator.T, identity) - np.kron(identity, generator) for generator in generators
    ]
    constraint_matrix = np.vstack(constraints)
    return dimension * dimension - _numerical_rank(constraint_matrix, tolerance=tolerance)


def _center_dimension(
    algebra_basis: Sequence[npt.NDArray[np.complex128]],
    generators: Sequence[npt.NDArray[np.complex128]],
    *,
    tolerance: float,
) -> int:
    if len(algebra_basis) == 0:
        return 0
    if len(generators) == 0:
        return len(algebra_basis)

    columns: list[npt.NDArray[np.complex128]] = []
    for basis_matrix in algebra_basis:
        commutators = [
            basis_matrix @ generator - generator @ basis_matrix for generator in generators
        ]
        columns.append(np.concatenate([commutator.reshape(-1) for commutator in commutators]))

    constraint_matrix = np.stack(columns, axis=1)
    return len(algebra_basis) - _numerical_rank(constraint_matrix, tolerance=tolerance)


def _numerical_rank(matrix: npt.ArrayLike, *, tolerance: float) -> int:
    arr = np.asarray(matrix, dtype=np.complex128)
    if arr.size == 0:
        return 0
    singular_values = np.linalg.svd(arr, compute_uv=False)
    if singular_values.size == 0:
        return 0
    cutoff = float(tolerance) * max(arr.shape) * max(1.0, float(singular_values[0]))
    return int(np.count_nonzero(singular_values > cutoff))


def _classify_error_algebra(
    *,
    code_dimension: int,
    algebra_dimension: int,
    commutant_dimension: int,
    center_dimension: int,
) -> ErrorAlgebraClassification:
    full_dimension = int(code_dimension) * int(code_dimension)
    if algebra_dimension == 1:
        return "scalar_algebra_subspace_code"
    if algebra_dimension == full_dimension and commutant_dimension == 1:
        return "full_matrix_algebra_no_protected_subsystem"
    if center_dimension > 1 and commutant_dimension > center_dimension:
        return "hybrid_block_or_subsystem_candidate"
    if center_dimension > 1:
        return "classical_block_structure"
    if commutant_dimension > 1:
        return "subsystem_code_candidate"
    return "irreducible_nonfull_inconclusive"


def _normalize_errors(
    errors: LocalErrorSet | Sequence[ErrorOperator],
) -> tuple[str, tuple[ErrorOperator, ...]]:
    if isinstance(errors, LocalErrorSet):
        return errors.name, errors.errors
    return "local_errors", tuple(errors)
