from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

import numpy as np
import numpy.typing as npt
import scipy.sparse as sp

from qlinks.basis import basis_configs_from_build_result
from qlinks.models import ModelBuildResult, SpinOneXYChainModel
from qlinks.open_system.local_recycling import embed_local_pattern_operator
from qlinks.open_system.operators import build_liouvillian

SpinOneXYLeftMultiplier = Literal["identity", "sx", "sz", "sz2"]


@dataclass(frozen=True, slots=True)
class SpinOneXYLindbladConstruction:
    """Paper-style local dark-detector Lindblad construction for spin-1 XY scars.

    The jumps have the form ``J_j = sqrt(gamma) V_j D_j`` with the local dark
    detector ``D_j = Sx_j Sx_{j+1} + Sy_j Sy_{j+1}``.  For the paper-like
    setting use ``left_multiplier='sx'``.  Diagonal multipliers such as ``'sz'``
    are useful when the build basis is restricted to a fixed total-Sz sector.
    """

    model: SpinOneXYChainModel
    build_result: ModelBuildResult
    hamiltonian: Any
    target_states: npt.NDArray[np.complex128]
    target_labels: tuple[str, ...]
    jumps: tuple[sp.csr_array, ...]
    detectors: tuple[sp.csr_array, ...]
    left_multipliers: tuple[sp.csr_array, ...]
    bond_ids: tuple[int, ...]
    left_multiplier: SpinOneXYLeftMultiplier
    gamma: float
    total_sz: int | None
    max_jump_residual: float
    jump_residuals: npt.NDArray[np.float64]
    hamiltonian_closure_residual: float
    liouvillian: sp.csr_array | None = None
    liouvillian_zero_mode_count: int | None = None

    @property
    def n_jumps(self) -> int:
        return len(self.jumps)

    @property
    def n_target_states(self) -> int:
        return int(self.target_states.shape[1])

    def to_summary_dict(self) -> dict[str, object]:
        return {
            "model": type(self.model).__name__,
            "length": int(self.model.length),
            "boundary_condition": str(self.model.boundary_condition),
            "total_sz": self.total_sz,
            "left_multiplier": self.left_multiplier,
            "gamma": float(self.gamma),
            "n_target_states": self.n_target_states,
            "target_labels": self.target_labels,
            "n_jumps": self.n_jumps,
            "bond_ids": self.bond_ids,
            "max_jump_residual": float(self.max_jump_residual),
            "hamiltonian_closure_residual": float(self.hamiltonian_closure_residual),
            "liouvillian_zero_mode_count": self.liouvillian_zero_mode_count,
        }


def spin_one_xy_scar_tower_states(
    *,
    basis_configs: npt.NDArray[np.integer],
    length: int | None = None,
    site_phase_offset: int = 0,
    normalize: bool = True,
    include_zero: bool = False,
) -> tuple[npt.NDArray[np.complex128], tuple[str, ...]]:
    """Return the spin-1 XY scar tower in a supplied product/sector basis.

    The tower is generated by ``(Q^dagger)^n |-1,...,-1>`` with
    ``Q^dagger = sum_j (-1)^(j + site_phase_offset) (S^+_j)^2``.  Up to a
    state-dependent normalization, the nonzero amplitudes are on configurations
    with ``n`` sites at ``+1`` and all remaining sites at ``-1``.

    If ``basis_configs`` is already restricted to one total-Sz sector, only the
    corresponding tower vector is nonzero unless ``include_zero=True``.
    """
    configs = np.asarray(basis_configs, dtype=np.int64)
    if configs.ndim != 2:
        raise ValueError("basis_configs must have shape (n_basis, n_variables).")

    n_basis, n_variables = configs.shape
    if length is None:
        length = int(n_variables)
    if int(length) != int(n_variables):
        raise ValueError("length must match the number of spin variables in basis_configs.")

    states: list[npt.NDArray[np.complex128]] = []
    labels: list[str] = []

    for n_raised in range(int(length) + 1):
        vector = np.zeros(n_basis, dtype=np.complex128)
        for basis_index, config in enumerate(configs):
            if np.any((config != -1) & (config != 1)):
                continue
            raised_sites = np.flatnonzero(config == 1)
            if raised_sites.size != n_raised:
                continue
            sign_power = int(np.sum(raised_sites) + site_phase_offset * n_raised)
            vector[basis_index] = -1.0 if sign_power % 2 else 1.0

        norm = float(np.linalg.norm(vector))
        if norm == 0.0:
            if include_zero:
                states.append(vector)
                labels.append(f"S_{n_raised}")
            continue
        if normalize:
            vector = vector / norm
        states.append(vector)
        labels.append(f"S_{n_raised}")

    if len(states) == 0:
        return np.zeros((n_basis, 0), dtype=np.complex128), ()

    return np.column_stack(states).astype(np.complex128, copy=False), tuple(labels)


def build_spin_one_xy_lindblad_construction(
    *,
    model: SpinOneXYChainModel,
    build_result: ModelBuildResult | None = None,
    target_states: npt.ArrayLike | None = None,
    target_labels: tuple[str, ...] | None = None,
    left_multiplier: SpinOneXYLeftMultiplier = "sx",
    gamma: float = 1.0,
    builder: Literal["sparse", "optimized"] = "sparse",
    check_liouvillian: bool = False,
    liouvillian_zero_tolerance: float = 1e-9,
) -> SpinOneXYLindbladConstruction:
    """Build paper-style spin-1 XY Lindblad jumps ``J_j = sqrt(gamma) V_j D_j``.

    Args:
        model: Spin-1 XY chain model.  Set ``model.total_sz`` to build within a
            fixed magnetization sector.
        build_result: Optional prebuilt Hamiltonian/basis for ``model``.
        target_states: Optional target-state matrix with one state per column.
            If omitted, the scar tower vectors present in ``build_result.basis``
            are generated automatically.
        target_labels: Optional labels for the columns of ``target_states``.
        left_multiplier: Local left factor ``V_j``.  Use ``"sx"`` for the
            paper-style DFS construction and diagonal choices such as ``"sz"``
            for fixed-total-Sz sector tests.
        gamma: Lindblad rate; jumps are scaled by ``sqrt(gamma)``.
        builder: Matrix builder used when ``build_result`` is not supplied.
        check_liouvillian: If true, assemble the Liouvillian and count zero
            eigenvalues.  This is intended only for small systems.
        liouvillian_zero_tolerance: Tolerance for zero-mode counting.

    Returns:
        Construction object containing jumps and dark/closure diagnostics.
    """
    if gamma < 0.0:
        raise ValueError("gamma must be nonnegative.")

    if build_result is None:
        build_result = model.build(
            builder=builder,
            basis_solver="dfs",
            sort_basis=True,
            on_missing="raise",
        )

    hamiltonian = build_result.hamiltonian.tocsr()
    basis_configs = basis_configs_from_build_result(build_result)

    if target_states is None:
        target_matrix, generated_labels = spin_one_xy_scar_tower_states(
            basis_configs=basis_configs,
            length=int(model.length),
        )
        target_labels = generated_labels
    else:
        target_matrix = _normalize_state_matrix(target_states, expected_dim=hamiltonian.shape[0])
        if target_labels is None:
            target_labels = tuple(f"target_{index}" for index in range(target_matrix.shape[1]))

    if target_matrix.shape[1] == 0:
        raise ValueError("No nonzero target states are present in the supplied basis.")

    if len(target_labels) != target_matrix.shape[1]:
        raise ValueError("target_labels length must match the number of target states.")

    detectors: list[sp.csr_array] = []
    left_multipliers: list[sp.csr_array] = []
    jumps: list[sp.csr_array] = []
    bond_ids: list[int] = []
    scale = float(np.sqrt(float(gamma)))

    for link in model.lattice.links:
        source_site = int(link.source)
        target_site = int(link.target)
        source_variable = int(model.layout.site_variable_index(source_site))
        target_variable = int(model.layout.site_variable_index(target_site))

        detector = _embed_spin_one_xy_bond_detector(
            basis_configs=basis_configs,
            variable_indices=(source_variable, target_variable),
        )
        left = _embed_spin_one_left_multiplier(
            basis_configs=basis_configs,
            variable_index=source_variable,
            multiplier=left_multiplier,
        )
        jump = (scale * (left @ detector)).tocsr()

        detectors.append(detector)
        left_multipliers.append(left)
        jumps.append(jump)
        bond_ids.append(int(link.id))

    jump_residuals = _jump_residual_matrix(jumps=tuple(jumps), target_states=target_matrix)
    max_jump_residual = float(np.max(jump_residuals)) if jump_residuals.size else 0.0
    closure_residual = _subspace_closure_residual(
        operator=hamiltonian,
        target_states=target_matrix,
    )

    liouvillian = None
    zero_mode_count = None
    if check_liouvillian:
        liouvillian = build_liouvillian(
            hamiltonian,
            jumps,
            sparse_format="csr",
        ).tocsr()
        eigenvalues = np.linalg.eigvals(liouvillian.toarray())
        zero_mode_count = int(np.count_nonzero(np.abs(eigenvalues) <= liouvillian_zero_tolerance))

    return SpinOneXYLindbladConstruction(
        model=model,
        build_result=build_result,
        hamiltonian=hamiltonian,
        target_states=target_matrix,
        target_labels=tuple(target_labels),
        jumps=tuple(jumps),
        detectors=tuple(detectors),
        left_multipliers=tuple(left_multipliers),
        bond_ids=tuple(bond_ids),
        left_multiplier=left_multiplier,
        gamma=float(gamma),
        total_sz=model.total_sz,
        max_jump_residual=max_jump_residual,
        jump_residuals=jump_residuals,
        hamiltonian_closure_residual=closure_residual,
        liouvillian=liouvillian,
        liouvillian_zero_mode_count=zero_mode_count,
    )


def _normalize_state_matrix(
    states: npt.ArrayLike,
    *,
    expected_dim: int,
) -> npt.NDArray[np.complex128]:
    array = np.asarray(states, dtype=np.complex128)
    if array.ndim == 1:
        array = array.reshape((-1, 1))
    if array.ndim != 2:
        raise ValueError("target_states must be a vector or a matrix with states in columns.")
    if int(array.shape[0]) != int(expected_dim):
        raise ValueError("target_states has incompatible Hilbert-space dimension.")

    normalized = np.array(array, dtype=np.complex128, copy=True)
    for column in range(normalized.shape[1]):
        norm = float(np.linalg.norm(normalized[:, column]))
        if norm == 0.0:
            raise ValueError("target_states contains a zero vector.")
        normalized[:, column] /= norm
    return normalized


def _spin_one_local_patterns(n_variables: int) -> tuple[tuple[int, ...], ...]:
    if n_variables == 1:
        return ((-1,), (0,), (1,))
    if n_variables == 2:
        return tuple((a, b) for a in (-1, 0, 1) for b in (-1, 0, 1))
    raise ValueError("Only one- and two-site spin-1 local patterns are supported.")


def _spin_one_sx_matrix() -> npt.NDArray[np.complex128]:
    values = (-1, 0, 1)
    value_to_index = {value: index for index, value in enumerate(values)}
    matrix = np.zeros((3, 3), dtype=np.complex128)
    for source_index, m in enumerate(values):
        if m < 1:
            target_index = value_to_index[m + 1]
            matrix[target_index, source_index] += 0.5 * np.sqrt(2 - m * (m + 1))
        if m > -1:
            target_index = value_to_index[m - 1]
            matrix[target_index, source_index] += 0.5 * np.sqrt(2 - m * (m - 1))
    return matrix


def _spin_one_sz_matrix() -> npt.NDArray[np.complex128]:
    return np.diag(np.asarray([-1, 0, 1], dtype=np.complex128))


def _spin_one_xy_bond_matrix() -> npt.NDArray[np.complex128]:
    patterns = _spin_one_local_patterns(2)
    pattern_to_index = {pattern: index for index, pattern in enumerate(patterns)}
    matrix = np.zeros((len(patterns), len(patterns)), dtype=np.complex128)

    for source_index, (mi, mj) in enumerate(patterns):
        if mi < 1 and mj > -1:
            target = (mi + 1, mj - 1)
            amp = 0.5 * np.sqrt(2 - mi * (mi + 1)) * np.sqrt(2 - mj * (mj - 1))
            matrix[pattern_to_index[target], source_index] += amp
        if mi > -1 and mj < 1:
            target = (mi - 1, mj + 1)
            amp = 0.5 * np.sqrt(2 - mi * (mi - 1)) * np.sqrt(2 - mj * (mj + 1))
            matrix[pattern_to_index[target], source_index] += amp

    return matrix


def _embed_spin_one_xy_bond_detector(
    *,
    basis_configs: npt.NDArray[np.integer],
    variable_indices: tuple[int, int],
) -> sp.csr_array:
    return embed_local_pattern_operator(
        basis_configs=basis_configs,
        variable_indices=tuple(int(index) for index in variable_indices),
        local_patterns=_spin_one_local_patterns(2),
        local_operator=_spin_one_xy_bond_matrix(),
    ).tocsr()


def _embed_spin_one_left_multiplier(
    *,
    basis_configs: npt.NDArray[np.integer],
    variable_index: int,
    multiplier: SpinOneXYLeftMultiplier,
) -> sp.csr_array:
    if multiplier == "identity":
        return sp.identity(basis_configs.shape[0], format="csr", dtype=np.complex128)
    if multiplier == "sx":
        local_operator = _spin_one_sx_matrix()
    elif multiplier == "sz":
        local_operator = _spin_one_sz_matrix()
    elif multiplier == "sz2":
        sz = _spin_one_sz_matrix()
        local_operator = sz @ sz
    else:
        raise ValueError('left_multiplier must be one of "identity", "sx", "sz", or "sz2".')

    return embed_local_pattern_operator(
        basis_configs=basis_configs,
        variable_indices=(int(variable_index),),
        local_patterns=_spin_one_local_patterns(1),
        local_operator=local_operator,
    ).tocsr()


def _jump_residual_matrix(
    *,
    jumps: tuple[sp.csr_array, ...],
    target_states: npt.NDArray[np.complex128],
) -> npt.NDArray[np.float64]:
    residuals = np.zeros((len(jumps), target_states.shape[1]), dtype=np.float64)
    for jump_index, jump in enumerate(jumps):
        action = jump @ target_states
        residuals[jump_index, :] = np.linalg.norm(action, axis=0)
    return residuals


def _subspace_closure_residual(
    *,
    operator: Any,
    target_states: npt.NDArray[np.complex128],
) -> float:
    q, _ = np.linalg.qr(target_states)
    action = operator @ q
    projected = q @ (q.conj().T @ action)
    return float(np.linalg.norm(action - projected))
