"""Exact symmetry helpers for the checkerboard square-QDM evidence workflow.

This module is intentionally experimental.  It resolves the full spatial
symmetry group shared by the positive checkerboard-phase family without
promoting the research convention into the supported :mod:`qlinks` API.

For ``chi(x,y)=(-1)^(x+y)`` the pattern-preserving translation subgroup is

    H = {(a,b) in Z_Lx x Z_4 : a+b even},

which is generated by ``T_x^2`` and the diagonal translation ``T_x T_y``.
At fixed positive phase the shifted reflections

    S_x = T_x R_x,   S_y = T_y R_y

are exact involutive symmetries, while the bare reflections ``R_x,R_y`` map
``phi -> -phi``.  For the thermal calculation we deliberately choose a generic character of
this subgroup, shared by every ``L_x=4N`` member,

    T_x T_y = exp(i*pi/2),   T_y^2 = +1.

The periodic-product cage has nonzero projection into this irrep on the tested
sequence.  Its generic diagonal momentum is not fixed by the checkerboard
point-group operations, so those operations exchange distinct translation
irreps rather than creating another block inside the selected sector.  This is
precisely the fully resolved situation required by the thermal protocol.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import numpy as np
import numpy.typing as npt
import scipy.sparse as sp
from qdm_checkerboard_large_strip import (
    _encoded_codes_to_packed_bytes,
    translation_permutation_from_binary_basis,
)

from qlinks.basis import Basis
from qlinks.caging.spectral import SymmetrySectorBasis
from qlinks.encoded import BinaryEncodedBasis


@dataclass(frozen=True, slots=True)
class CheckerboardResolvedSector:
    """Fully resolved positive-phase checkerboard symmetry sector."""

    sector: SymmetrySectorBasis
    generator_names: tuple[str, ...]
    generator_characters: tuple[complex, ...]
    generator_orders: tuple[int, ...]
    translation_group_size: int
    point_group_little_group: str


def square_qdm_variable_permutation_from_site_map(
    model: Any,
    transform: Callable[[int, int], tuple[int, int]],
) -> npt.NDArray[np.int64]:
    """Return ``new_config = old_config[var_perm]`` for a square-lattice site map.

    Dimer variables live on undirected physical links.  Mapping link endpoints
    rather than relying on an oriented link ``kind`` makes reflections and
    rotations exact even when they reverse the stored source/target ordering.
    """

    cell_to_site = {
        (int(site.cell[0]), int(site.cell[1])): int(site.id) for site in model.lattice.sites
    }
    edge_to_variable = {
        frozenset((int(link.source), int(link.target))): int(
            model.layout.link_variable_index(int(link.id))
        )
        for link in model.lattice.links
    }
    target_for_source = np.empty(model.lattice.num_links, dtype=np.int64)
    for link in model.lattice.links:
        source_variable = int(model.layout.link_variable_index(int(link.id)))
        endpoints: list[int] = []
        for site_id in (int(link.source), int(link.target)):
            x, y = model.lattice.sites[site_id].cell
            tx, ty = transform(int(x), int(y))
            endpoints.append(cell_to_site[(tx % int(model.lx), ty % int(model.ly))])
        try:
            target_for_source[source_variable] = edge_to_variable[frozenset(endpoints)]
        except KeyError as exc:
            raise ValueError(
                "site transform does not preserve the square-lattice link set"
            ) from exc

    source_for_target = np.empty_like(target_for_source)
    source_for_target[target_for_source] = np.arange(target_for_source.size, dtype=np.int64)
    return source_for_target


def binary_basis_permutation_from_variable_permutation(
    basis: Basis | BinaryEncodedBasis,
    variable_permutation: npt.ArrayLike,
    *,
    packed_index: Mapping[bytes | int, int],
    chunk_size: int = 32768,
) -> npt.NDArray[np.int64]:
    """Return the basis-index permutation induced by a binary variable map."""

    variables = np.asarray(variable_permutation, dtype=np.int64).reshape(-1)
    if variables.size != basis.n_variables:
        raise ValueError("variable_permutation has incompatible length")
    if np.unique(variables).size != variables.size:
        raise ValueError("variable_permutation must be a permutation")
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")

    result = np.empty(basis.n_states, dtype=np.int64)
    if isinstance(basis, BinaryEncodedBasis):
        byte_width = (basis.n_variables + 7) // 8
        for start in range(0, basis.n_states, int(chunk_size)):
            stop = min(start + int(chunk_size), basis.n_states)
            packed = _encoded_codes_to_packed_bytes(
                basis.codes[start:stop], n_variables=basis.n_variables
            )
            unpacked = np.unpackbits(packed, axis=1, bitorder="little")[:, : basis.n_variables]
            transformed = unpacked[:, variables]
            transformed_packed = np.packbits(transformed, axis=1, bitorder="little")
            if transformed_packed.shape[1] != byte_width:
                raise RuntimeError("unexpected packed width after symmetry transform")
            for offset, row in enumerate(transformed_packed):
                code = int.from_bytes(row.tobytes(), "little", signed=False)
                try:
                    result[start + offset] = int(packed_index[code])
                except KeyError as exc:
                    raise ValueError(
                        "symmetry-transformed state is absent from encoded basis"
                    ) from exc
        return result

    states = np.asarray(basis.states)
    for start in range(0, basis.n_states, int(chunk_size)):
        stop = min(start + int(chunk_size), basis.n_states)
        transformed = states[start:stop, variables]
        packed = np.packbits(transformed.astype(np.uint8, copy=False), axis=1, bitorder="little")
        for offset, row in enumerate(packed):
            try:
                result[start + offset] = int(packed_index[row.tobytes()])
            except KeyError as exc:
                raise ValueError("symmetry-transformed state is absent from basis") from exc
    return result


def _compose(left: npt.ArrayLike, right: npt.ArrayLike) -> npt.NDArray[np.int64]:
    """Permutation for ``U_left U_right`` under ``U|i> = |p[i]>``."""

    p_left = np.asarray(left, dtype=np.int64).reshape(-1)
    p_right = np.asarray(right, dtype=np.int64).reshape(-1)
    if p_left.size != p_right.size:
        raise ValueError("permutations have incompatible sizes")
    return p_left[p_right]


def character_sector_basis_from_generators(
    permutations: Sequence[npt.ArrayLike],
    characters: Sequence[complex],
    *,
    labels: Mapping[str, object] | None = None,
    tolerance: float = 1.0e-10,
) -> SymmetrySectorBasis:
    """Build a one-dimensional group-character sector by Cayley-orbit propagation.

    The generators need not commute.  The requested characters must define a
    consistent one-dimensional representation of their relations.  Orbits with
    incompatible stabilizers are discarded exactly as in ordinary momentum
    projection.  This is the memory-scalable route used for the positive-phase
    checkerboard space group.
    """

    perms = tuple(np.asarray(value, dtype=np.int64).reshape(-1) for value in permutations)
    chars = tuple(complex(value) for value in characters)
    if not perms or len(perms) != len(chars):
        raise ValueError("permutations and characters must be nonempty and have equal length")
    n = int(perms[0].size)
    if any(value.size != n for value in perms):
        raise ValueError("all permutations must have equal size")
    for value in perms:
        if np.unique(value).size != n or np.any(value < 0) or np.any(value >= n):
            raise ValueError("each generator must be a permutation of range(n)")
    if any(abs(abs(value) - 1.0) > tolerance for value in chars):
        raise ValueError("generator characters must have unit modulus")

    visited = np.zeros(n, dtype=bool)
    rows: list[int] = []
    columns: list[int] = []
    data: list[complex] = []
    orbit_sizes: list[int] = []
    column = 0

    for seed in range(n):
        if visited[seed]:
            continue
        coefficient: dict[int, complex] = {int(seed): 1.0 + 0.0j}
        queue = [int(seed)]
        compatible = True
        while queue:
            state = queue.pop()
            value = coefficient[state]
            for permutation, character in zip(perms, chars, strict=True):
                nxt = int(permutation[state])
                # U_g |psi> = chi_g |psi> implies c_{g s}=c_s/chi_g.
                expected = value / character
                if nxt in coefficient:
                    if abs(coefficient[nxt] - expected) > tolerance:
                        compatible = False
                else:
                    coefficient[nxt] = expected
                    queue.append(nxt)
        orbit = tuple(coefficient)
        for state in orbit:
            visited[state] = True
        if not compatible:
            continue
        norm = float(np.sqrt(sum(abs(value) ** 2 for value in coefficient.values())))
        if norm <= tolerance:
            continue
        for state, value in coefficient.items():
            rows.append(int(state))
            columns.append(column)
            data.append(complex(value / norm))
        orbit_sizes.append(len(orbit))
        column += 1

    basis = sp.csr_array(
        (np.asarray(data, dtype=np.complex128), (rows, columns)), shape=(n, column)
    )
    gram = basis.conj().T @ basis
    residual = float(sp.linalg.norm(gram - sp.eye(column, dtype=np.complex128, format="csr")))
    metadata = {} if labels is None else dict(labels)
    metadata.update(
        {
            "symmetry": "checkerboard_space_group_character",
            "generator_characters": tuple(chars),
            "orbit_sizes": tuple(int(value) for value in orbit_sizes),
        }
    )
    return SymmetrySectorBasis(basis=basis, labels=metadata, unitarity_residual=residual)


def checkerboard_positive_phase_permutations(
    model: Any,
    basis: Basis | BinaryEncodedBasis,
    *,
    packed_index: Mapping[bytes | int, int],
    chunk_size: int = 32768,
) -> dict[str, npt.NDArray[np.int64]]:
    """Return generators/audit permutations for the positive checkerboard family."""

    tx1 = translation_permutation_from_binary_basis(
        model, basis, packed_index=packed_index, dx=1, chunk_size=chunk_size
    )
    ty1 = translation_permutation_from_binary_basis(
        model, basis, packed_index=packed_index, dy=1, chunk_size=chunk_size
    )
    tx2 = translation_permutation_from_binary_basis(
        model, basis, packed_index=packed_index, dx=2, chunk_size=chunk_size
    )
    ty2 = translation_permutation_from_binary_basis(
        model, basis, packed_index=packed_index, dy=2, chunk_size=chunk_size
    )
    tdiag = _compose(tx1, ty1)

    rx_variables = square_qdm_variable_permutation_from_site_map(model, lambda x, y: (-x, y))
    ry_variables = square_qdm_variable_permutation_from_site_map(model, lambda x, y: (x, -y))
    rx = binary_basis_permutation_from_variable_permutation(
        basis, rx_variables, packed_index=packed_index, chunk_size=chunk_size
    )
    ry = binary_basis_permutation_from_variable_permutation(
        basis, ry_variables, packed_index=packed_index, chunk_size=chunk_size
    )
    sx = _compose(tx1, rx)
    sy = _compose(ty1, ry)
    c2 = _compose(sx, sy)
    return {
        "Tx": tx1,
        "Ty": ty1,
        "Tx2": tx2,
        "Ty2": ty2,
        "Tdiag": tdiag,
        "Rx": rx,
        "Ry": ry,
        "Sx": sx,
        "Sy": sy,
        "C2": c2,
    }


def checkerboard_fully_resolved_sector(
    model: Any,
    basis: Basis | BinaryEncodedBasis,
    *,
    packed_index: Mapping[bytes | int, int],
    repeats: int,
    chunk_size: int = 32768,
) -> tuple[CheckerboardResolvedSector, dict[str, npt.NDArray[np.int64]]]:
    """Build the fully resolved generic translation irrep used for thermal data.

    The pattern-preserving translation group is generated independently by
    ``Tdiag = T_x T_y`` (order ``L_x``) and ``Ty2 = T_y^2`` (order two).
    Choosing ``Tdiag=i`` and ``Ty2=+1`` gives the same physical diagonal
    momentum ``pi/2`` for every ``L_x=4N`` and avoids point-group little-group
    degeneracies.
    """

    if int(model.ly) != 4 or int(model.lx) != 4 * int(repeats):
        raise ValueError("checkerboard fixed-width sector requires Lx=4*repeats and Ly=4")
    permutations = checkerboard_positive_phase_permutations(
        model, basis, packed_index=packed_index, chunk_size=chunk_size
    )
    names = ("Tdiag", "Ty2")
    chars = (1.0j, 1.0 + 0.0j)
    orders = (int(model.lx), 2)
    sector = character_sector_basis_from_generators(
        tuple(permutations[name] for name in names),
        chars,
        labels={
            "Tdiag_momentum_angle": float(np.pi / 2.0),
            "Tdiag_momentum_index": int(model.lx) // 4,
            "Ty2_character": 1,
            "checkerboard_translation_group_size": 2 * int(model.lx),
            "checkerboard_translation_condition": "a+b even",
            "point_group_little_group": "trivial_at_kdiag_pi_over_2",
        },
    )
    return (
        CheckerboardResolvedSector(
            sector=sector,
            generator_names=names,
            generator_characters=chars,
            generator_orders=orders,
            translation_group_size=2 * int(model.lx),
            point_group_little_group="trivial_at_kdiag_pi_over_2",
        ),
        permutations,
    )
