"""Analysis of caged states and local caging operators.

The subpackage separates three distinct questions:

* :mod:`environment` asks whether exterior degrees of freedom can be removed
  when constructing a bounded local caging operator;
* :mod:`local_structure` analyzes local reduced-state/operator structure; and
* :mod:`support` / :mod:`support_morphology` describe the resulting local
  support without treating it as a classification of the eigenstate.
"""

from qlinks.caging.analysis.environment import (
    CollectiveCancellationMode,
    CollectiveCancellationReport,
    EnvironmentProbeDetailLabel,
    EnvironmentReductionConfig,
    EnvironmentReductionReport,
    EnvironmentRemovalMechanismLabel,
    EnvironmentRemovalProbeReport,
    EnvironmentRemovalSummary,
    ReducedIZMonitorComponentGroup,
    ReducedIZMonitorDecomposition,
    ReducedIZProbeSupport,
    SectorPolicy,
    diagnose_cage_environment_reduction,
    diagnose_environment_reduction,
    group_reduced_iz_monitor_reports,
    group_reduced_iz_reports_by_connected_support,
    group_reduced_iz_reports_by_exact_support,
    reduced_iz_component_groups_from_reports,
    reduced_iz_probe_support_from_report,
    select_reduced_iz_monitor_reports,
    select_reduced_iz_monitor_reports_from_zero_reports,
    support_key_for_zero_report,
    support_key_from_mask,
)
from qlinks.caging.analysis.local_structure import (
    CageLocalStructureReport,
    CommutantAlgebraDiagnostic,
    FockSpaceAutomorphismDiagnostic,
    LocalAnnihilatorDiagnostic,
    LocalClassicalPatternSector,
    LocalCoherentPatternPair,
    LocalPlaquetteActivityReport,
    LocalReducedDensityMatrixReadout,
    LocalStructureReadoutReport,
    OperatorStateActionDiagnostic,
    SupportPermutationDiagnostic,
    analyze_local_rdm_structure,
    commutant_algebra_diagnostic_from_operator_basis,
    fock_space_automorphism_diagnostic,
    fock_space_automorphism_diagnostic_for_cage_state,
    local_annihilator_diagnostic_from_operators,
    local_reduced_density_matrix_readout_from_state,
    local_structure_report_from_environment_report,
    local_structure_report_from_readouts,
    reduced_iz_local_rdm_readouts_from_report,
)
from qlinks.caging.analysis.support import (
    EnvironmentReductionSupportPolicy,
    LocalCagingRegionSupport,
    LocalCancellationPatternSupport,
    distinct_local_cancellation_pattern_supports,
    extract_local_caging_region,
)
from qlinks.caging.analysis.support_morphology import (
    FockSupportMorphology,
    FockSupportMorphologyLabel,
    RealSpaceSupportMorphology,
    RealSpaceSupportMorphologyLabel,
    SupportMorphologyConfig,
    SupportMorphologyReport,
    analyze_fock_support_morphology,
    analyze_real_space_support_morphology,
    analyze_support_morphology,
)
from qlinks.caging.analysis.transitions import (
    LocalTransitionPattern,
    local_transition_pattern_signature,
    transition_pattern_key,
)

__all__ = [
    "CageLocalStructureReport",
    "CollectiveCancellationMode",
    "CollectiveCancellationReport",
    "CommutantAlgebraDiagnostic",
    "EnvironmentProbeDetailLabel",
    "EnvironmentReductionConfig",
    "EnvironmentReductionReport",
    "EnvironmentReductionSupportPolicy",
    "EnvironmentRemovalMechanismLabel",
    "EnvironmentRemovalProbeReport",
    "EnvironmentRemovalSummary",
    "FockSpaceAutomorphismDiagnostic",
    "FockSupportMorphology",
    "FockSupportMorphologyLabel",
    "LocalAnnihilatorDiagnostic",
    "LocalCagingRegionSupport",
    "LocalCancellationPatternSupport",
    "LocalClassicalPatternSector",
    "LocalCoherentPatternPair",
    "LocalPlaquetteActivityReport",
    "LocalReducedDensityMatrixReadout",
    "LocalStructureReadoutReport",
    "LocalTransitionPattern",
    "OperatorStateActionDiagnostic",
    "RealSpaceSupportMorphology",
    "RealSpaceSupportMorphologyLabel",
    "ReducedIZMonitorComponentGroup",
    "ReducedIZMonitorDecomposition",
    "ReducedIZProbeSupport",
    "SectorPolicy",
    "SupportMorphologyConfig",
    "SupportMorphologyReport",
    "SupportPermutationDiagnostic",
    "analyze_fock_support_morphology",
    "analyze_local_rdm_structure",
    "analyze_real_space_support_morphology",
    "analyze_support_morphology",
    "commutant_algebra_diagnostic_from_operator_basis",
    "diagnose_cage_environment_reduction",
    "diagnose_environment_reduction",
    "distinct_local_cancellation_pattern_supports",
    "extract_local_caging_region",
    "fock_space_automorphism_diagnostic",
    "fock_space_automorphism_diagnostic_for_cage_state",
    "group_reduced_iz_monitor_reports",
    "group_reduced_iz_reports_by_connected_support",
    "group_reduced_iz_reports_by_exact_support",
    "local_annihilator_diagnostic_from_operators",
    "local_reduced_density_matrix_readout_from_state",
    "local_structure_report_from_environment_report",
    "local_structure_report_from_readouts",
    "local_transition_pattern_signature",
    "reduced_iz_component_groups_from_reports",
    "reduced_iz_local_rdm_readouts_from_report",
    "reduced_iz_probe_support_from_report",
    "select_reduced_iz_monitor_reports",
    "select_reduced_iz_monitor_reports_from_zero_reports",
    "support_key_for_zero_report",
    "support_key_from_mask",
    "transition_pattern_key",
]
